import Head from 'next/head';
import Message from '../components/message';
import { useState, useEffect } from 'react';
import { db } from '../utils/firebase';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';

export default function Home() {
  const [allMessages, setAllMessages] = useState<any[]>([]);

  const getMessages = async () => {
    const collectionRef = collection(db, 'messages');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllMessages(snapshot.docs.map((message) => ({ ...message.data(), id: message.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getMessages();
  }, []);

  console.log(allMessages);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {allMessages?.map((message) => (
        <Message key={message.id} {...message}></Message>
      ))}
    </div>
  );
}
